# Generated by Django 4.2 on 2023-04-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.SmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('number', models.SmallIntegerField(blank=True, null=True)),
                ('teacher', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=50)),
            ],
        ),
    ]
