# Generated by Django 4.2 on 2023-04-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='STinfo',
            new_name='StudentInfo',
        ),
    ]
