# Generated by Django 4.2 on 2023-04-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='kind',
            field=models.CharField(default='present', max_length=50),
        ),
    ]
