# Generated by Django 4.2 on 2023-04-27 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATbook', '0002_alter_attend_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfo',
            name='attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_attendance', to='ATbook.attend'),
        ),
        migrations.AlterField(
            model_name='attendanceinfo',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_student', to='ATbook.student'),
        ),
        migrations.AlterField(
            model_name='attendanceinfo',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_teacher', to='ATbook.teacher'),
        ),
    ]
