# Generated by Django 4.2 on 2023-04-23 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATbook', '0005_attendanceinfo_date_alter_attendanceinfo_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='student',
        ),
        migrations.RemoveField(
            model_name='attendanceinfo',
            name='teacher',
        ),
        migrations.AddField(
            model_name='attendanceinfo',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ATbook.teacher'),
        ),
    ]
