# Generated by Django 4.2 on 2023-04-23 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ATbook', '0006_remove_teacher_student_remove_attendanceinfo_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceinfo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
