# Generated by Django 4.2 on 2023-05-11 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATbook', '0006_period_alter_teacher_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourattend',
            name='hour_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_hour_1', to='ATbook.attend'),
        ),
        migrations.AlterField(
            model_name='hourattend',
            name='hour_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_hour_2', to='ATbook.attend'),
        ),
        migrations.AlterField(
            model_name='hourattend',
            name='hour_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_hour_3', to='ATbook.attend'),
        ),
        migrations.AlterField(
            model_name='hourattend',
            name='hour_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_hour_4', to='ATbook.attend'),
        ),
        migrations.AlterField(
            model_name='hourattend',
            name='hour_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_hour_5', to='ATbook.attend'),
        ),
        migrations.AlterField(
            model_name='hourattend',
            name='hour_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_hour_6', to='ATbook.attend'),
        ),
        migrations.AlterField(
            model_name='hourattend',
            name='hour_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_hour_7', to='ATbook.attend'),
        ),
        migrations.AlterField(
            model_name='hourattend',
            name='hour_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_hour_8', to='ATbook.attend'),
        ),
        migrations.AlterField(
            model_name='hourattend',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_hr', to='ATbook.attend'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.SmallIntegerField(null=True),
        ),
    ]
