# Generated by Django 4.2 on 2023-05-14 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATbook', '0007_alter_hourattend_hour_1_alter_hourattend_hour_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindAttend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='hourattend',
            name='hour_1',
        ),
        migrations.RemoveField(
            model_name='hourattend',
            name='hour_2',
        ),
        migrations.RemoveField(
            model_name='hourattend',
            name='hour_3',
        ),
        migrations.RemoveField(
            model_name='hourattend',
            name='hour_4',
        ),
        migrations.RemoveField(
            model_name='hourattend',
            name='hour_5',
        ),
        migrations.RemoveField(
            model_name='hourattend',
            name='hour_6',
        ),
        migrations.RemoveField(
            model_name='hourattend',
            name='hour_7',
        ),
        migrations.RemoveField(
            model_name='hourattend',
            name='hour_8',
        ),
        migrations.RemoveField(
            model_name='hourattend',
            name='hr',
        ),
        migrations.AddField(
            model_name='attend',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_hourattend', to='ATbook.hourattend'),
        ),
        migrations.AddField(
            model_name='hourattend',
            name='hour',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_hour', to='ATbook.hourattend'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_kindattend', to='ATbook.kindattend'),
        ),
    ]
