# Generated by Django 4.2 on 2023-05-14 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATbook', '0008_kindattend_remove_hourattend_hour_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attend',
            name='time',
        ),
        migrations.AddField(
            model_name='attendanceinfo',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_hourattend', to='ATbook.hourattend'),
        ),
        migrations.AlterField(
            model_name='attend',
            name='kind',
            field=models.CharField(blank=True, default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendanceinfo',
            name='attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_attendance', to='ATbook.attend'),
        ),
        migrations.DeleteModel(
            name='KindAttend',
        ),
    ]
