# Generated by Django 4.2 on 2023-06-30 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ATbook', '0009_remove_attend_time_attendanceinfo_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='period',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='time',
        ),
        migrations.RenameField(
            model_name='attend',
            old_name='kind',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='attendanceinfo',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendanceinfo',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameModel(
            old_name='HourAttend',
            new_name='Hour',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='hour_f',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ATbook.hour'),
        ),
        migrations.AddField(
            model_name='subject',
            name='period_f',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ATbook.period'),
        ),
        migrations.AddField(
            model_name='attendanceinfo',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_subject', to='ATbook.subject'),
        ),
    ]
