# Generated by Django 4.2 on 2023-06-30 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ATbook', '0010_subject_remove_teacher_period_remove_teacher_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_teacher_f', to=settings.AUTH_USER_MODEL),
        ),
    ]
