# Generated by Django 4.2 on 2023-06-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0001_initial'),
        ('ATbook', '0011_subject_teacher_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Department_f',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_department', to='mylogin.department'),
        ),
    ]
