# Generated by Django 4.2 on 2023-06-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATbook', '0013_remove_subject_department_f_remove_subject_hour_f_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendanceinfo',
            old_name='subject_f',
            new_name='subject',
        ),
    ]
