# Generated by Django 4.2 on 2023-07-01 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ATbook', '0015_alter_attendanceinfo_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceinfo',
            name='attendance',
        ),
        migrations.AddField(
            model_name='attendanceinfo',
            name='first_half',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_first_half', to='ATbook.attend'),
        ),
        migrations.AddField(
            model_name='attendanceinfo',
            name='latter_half',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_latter_half', to='ATbook.attend'),
        ),
        migrations.AlterField(
            model_name='attendanceinfo',
            name='student',
            field=models.ForeignKey(limit_choices_to=models.Q(('departments__name', 'AD'), ('departments__name', 'CS'), ('departments__name', 'ME'), ('departments__name', 'EE'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendanceinfo',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'departments__name': 'Teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
