# Generated by Django 4.2 on 2023-09-26 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ATbook', '0016_remove_attendanceinfo_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accidental_absence', models.IntegerField(blank=True, default=0, null=True)),
                ('class_absence', models.IntegerField(blank=True, default=0, null=True)),
                ('sick_absence', models.IntegerField(blank=True, default=0, null=True)),
                ('leaving_early', models.IntegerField(blank=True, default=0, null=True)),
                ('tardiness', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attendanceinfo',
            name='student',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'Student')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendanceinfo',
            name='teacher',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'HomeroomTeacher'), ('groups__name', 'SubjectTeacher'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
