# Generated by Django 4.2 on 2023-09-26 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ATbook', '0017_total_alter_attendanceinfo_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='student',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'Student')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_Total_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
