# Generated by Django 4.2 on 2023-09-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATbook', '0018_total_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Total',
        ),
    ]
