# Generated by Django 4.2 on 2023-10-12 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ATbook", "0019_delete_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="total",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_status",
                        to="ATbook.status",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("groups__name", "Student")),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_total_student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
