# Generated by Django 4.2 on 2023-10-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ATbook", "0021_remove_total_state_total_late_total_leave_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="total",
            name="absent",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="total",
            name="present",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
