# Generated by Django 4.2 on 2023-06-30 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('Department_f', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_department', to='mylogin.department')),
                ('hour_f', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mylogin.hour')),
                ('period_f', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mylogin.period')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_attendance', to='mylogin.subject'),
        ),
    ]
