# Generated by Django 4.2 on 2023-06-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0002_hour_period_subject_user_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Department_f',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='hour_f',
            new_name='hour',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='period_f',
            new_name='period',
        ),
    ]
