# Generated by Django 4.2 on 2023-06-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0003_rename_department_f_subject_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Subject',
        ),
        migrations.AddField(
            model_name='user',
            name='Subject',
            field=models.ManyToManyField(blank=True, related_name='related_attendance', to='mylogin.subject', verbose_name='所属'),
        ),
    ]
