# Generated by Django 4.2 on 2023-06-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0004_remove_user_subject_user_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Subject',
            field=models.ManyToManyField(blank=True, related_name='related_attendance', to='mylogin.subject', verbose_name='科目'),
        ),
    ]
