# Generated by Django 4.2 on 2023-06-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0005_alter_user_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='Department',
            new_name='department',
        ),
        migrations.AddField(
            model_name='subject',
            name='date',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mylogin.date'),
        ),
    ]
