# Generated by Django 4.2 on 2023-07-02 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0006_date_rename_department_subject_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='date',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_date', to='mylogin.date'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='hour',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_hour', to='mylogin.hour'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='period',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_period', to='mylogin.period'),
        ),
    ]
