# Generated by Django 4.2 on 2023-07-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0007_alter_subject_date_alter_subject_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Subject',
            field=models.ManyToManyField(blank=True, related_name='related_Subject', to='mylogin.subject', verbose_name='科目'),
        ),
    ]
