# Generated by Django 4.2 on 2023-09-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0008_alter_user_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Number_of_classes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
