# Generated by Django 4.2 on 2023-12-08 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0010_user_accidental_absence_user_class_absence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': '科目管理'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='Number_of_classes',
        ),
        migrations.AlterField(
            model_name='subject',
            name='date',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_date', to='mylogin.date', verbose_name='曜日'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_department', to='mylogin.department', verbose_name='学科'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='hour',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_hour', to='mylogin.hour', verbose_name='時限'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='period',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_period', to='mylogin.period', verbose_name='期間'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='科目'),
        ),
    ]
